---
# tasks file for roles/osp-instance-delete
  - name: Fetch Instance Info
    os_server_info:
      cloud: openstack
      filters:
        vm_state: active
    register: result

  - name: Delete instances
    os_server:
      cloud: openstack
      name: "{{ item.name }}"
      state: absent
    loop: "{{result.ansible_facts.openstack_servers}}"
