---
# vars file for osp.servers
osp_servers:
  - { name: 'frontend', state: 'present', image: 'rhel-guest', key_name: 'ansible_ssh', flavor: 'm1.medium', security_group: 'frontend', meta_group: 'frontends', meta_deployment_name: 'QA' }
  - { name: 'app1', state: 'present', image: 'rhel-guest', key_name: 'ansible_ssh', flavor: 'm1.medium', security_group: 'apps', meta_group: 'apps', meta_deployment_name: 'QA' }
  - { name: 'app2', state: 'present', image: 'rhel-guest', key_name: 'ansible_ssh', flavor: 'm1.medium', security_group: 'apps', meta_group: 'apps', meta_deployment_name: 'QA' }
  - { name: 'db', state: 'present', image: 'rhel-guest', key_name: 'ansible_ssh', flavor: 'm1.medium', security_group: 'db', meta_group: 'appdbs', meta_deployment_name: 'QA' }
