---
- name: Install {{ payload }}
  yum:
    name: "{{ payload }}"
    state: latest

- name: Create Tomcat default web directory
  file:
    path: "{{ tomcat_web_root }}"
    state: directory
  notify:
    - start {{ payload }}
    - enable {{ payload }}

- name: Configure tomcat index
  template:
    src: index.html.j2
    dest: "{{ tomcat_web_root }}/index.html"
    mode: 0644
  notify:
    - restart {{ payload }}
